---
abstract: 'Things for Online Encyclopedia of Integer Sequences.'
author:
  - 'Kevin Ryde <user42_kevin@yahoo.com.au>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.141520'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-OEIS
no_index:
  directory:
    - t
    - inc
    - devel
    - xt
recommends:
  File::Map: '0'
  Scalar::Util: '0'
requires:
  Class::Singleton: '0'
  File::HomeDir: '0'
  File::Spec: '0'
  Module::Load: '0'
  Search::Dict: '0'
  Test::More: '0'
  constant::defer: '0'
  perl: '5.006'
resources:
  homepage: http://user42.tuxfamily.org/math-oeis/index.html
  license: http://www.gnu.org/licenses/gpl.html
version: '2'
